demos:
  - name: "small"
    description: "紧凑集中的图案"
    description_en: "Compact, concentrated pattern"
    filename: "demo_small.gif"
    limit_x_min: -15
    limit_x_max: 15
    limit_y_min: -15
    limit_y_max: 15

  - name: "wide"
    description: "水平拉伸的窄图案"
    description_en: "Horizontally stretched, narrow pattern"
    filename: "demo_wide.gif"
    limit_x_min: -11111111195
    limit_x_max: 11111111195
    limit_y_min: -15
    limit_y_max: 15

  - name: "current"
    description: "当前默认配置"
    description_en: "Current default configuration"
    filename: "demo_current.gif"
    limit_x_min: -11111111195
    limit_x_max: 11111111195
    limit_y_min: -95
    limit_y_max: 95

  - name: "moderate"
    description: "中等范围，平衡图案"
    description_en: "Moderate range, balanced patterns"
    filename: "demo_large.gif"
    limit_x_min: -500
    limit_x_max: 500
    limit_y_min: -500
    limit_y_max: 500

  - name: "asymmetric_y"
    description: "Y轴不对称，负向扩展"
    description_en: "Y-axis asymmetric, negative extension"
    filename: "demo_asymmetric_y.gif"
    limit_x_min: -500
    limit_x_max: 500
    limit_y_min: -500
    limit_y_max: 100

  - name: "asymmetric_x"
    description: "X轴不对称，正向偏移"
    description_en: "X-axis asymmetric, positive offset"
    filename: "demo_asymmetric_x.gif"
    limit_x_min: 0
    limit_x_max: 1000
    limit_y_min: -250
    limit_y_max: 250

  - name: "quarter"
    description: "第一象限图案"
    description_en: "First quadrant pattern"
    filename: "demo_quarter.gif"
    limit_x_min: 0
    limit_x_max: 500
    limit_y_min: 0
    limit_y_max: 500
